# Generated by Django 4.1.1 on 2022-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrappedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, default="", max_length=100)),
                ("price", models.TextField(blank=True, default="", max_length=100)),
                ("perc_1h", models.TextField(blank=True, default="", max_length=100)),
                ("perc_24h", models.TextField(blank=True, default="", max_length=100)),
                ("perc_7d", models.TextField(blank=True, default="", max_length=100)),
                (
                    "market_cap",
                    models.TextField(blank=True, default="", max_length=100),
                ),
                (
                    "volume_24h",
                    models.TextField(blank=True, default="", max_length=100),
                ),
                (
                    "circulating_supply",
                    models.TextField(blank=True, default="", max_length=100),
                ),
            ],
        ),
    ]
