# Generated by Django 4.1.1 on 2022-09-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="scrappeddata", name="id",),
        migrations.AlterField(
            model_name="scrappeddata",
            name="name",
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
